=== Daniel-RodriguezFernandez/Avila-Desktop/xml/rutas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.uniovi.es" elementFormDefault="qualified"
    targetNamespace="http://www.uniovi.es" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="rutas">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="3" maxOccurs="unbounded" ref="ruta" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="ruta">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="horario" />
                <xs:element ref="descripcion" />
                <xs:element ref="personasAdecuadas" />
                <xs:element ref="inicio" />
                <xs:element ref="referencias" />
                <xs:element ref="hitos" />
                <xs:element ref="planimetria" />
                <xs:element ref="altimetria" />
            </xs:sequence>

            <xs:attribute name="id" type="xs:ID" use="required" />

            <xs:attribute name="nombre" type="xs:string" use="required" />
            <xs:attribute name="tipo" type="xs:string" use="required" />

            <xs:attribute name="medio" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="A pie" />
                        <xs:enumeration value="Bicicleta" />
                        <xs:enumeration value="Coche" />
                        <xs:enumeration value="Caballo" />
                        <xs:enumeration value="Mixto" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>

            <xs:attribute name="agencia" type="xs:string" use="required" />

            <xs:attribute name="recomendacion" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minInclusive value="0" />
                        <xs:maxInclusive value="10" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>

        </xs:complexType>
    </xs:element>


    <xs:element name="horario">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="1" ref="fecha_inicio" />
                <xs:element minOccurs="0" maxOccurs="1" ref="hora_inicio" />
                <xs:element ref="duracion" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="fecha_inicio" type="xs:date" />

    <xs:element name="hora_inicio" type="xs:time" />

    <xs:element name="duracion" type="xs:duration" />
    <xs:element name="descripcion" type="xs:string" />
    <xs:element name="personasAdecuadas" type="xs:string" />
    <xs:element name="inicio">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="lugar" />
                <xs:element ref="direccion" />
                <xs:element ref="coordenadas" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="lugar" type="xs:string" />
    <xs:element name="direccion" type="xs:string" />


    <xs:element name="coordenadas">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="longitud" />
                <xs:element ref="latitud" />
                <xs:element ref="altitud" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="latitud">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                <xs:minInclusive value="-90" />
                <xs:maxInclusive value="90" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="longitud">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                <xs:minInclusive value="-180" />
                <xs:maxInclusive value="180" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="altitud" type="xs:decimal" />

    <xs:element name="referencias">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="referencia" type="xs:anyURI" />


    <xs:element name="hitos">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="5" maxOccurs="unbounded" ref="hito" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="hito">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="1" ref="descripcion" />
                <xs:element ref="coordenadas" />
                <xs:element minOccurs="1" maxOccurs="1" ref="distancia" />
                <xs:element minOccurs="0" maxOccurs="1" ref="fotografias" />
                <xs:element minOccurs="0" maxOccurs="1" ref="videos" />
            </xs:sequence>
            <xs:attribute name="nombre" type="xs:string" use="optional" />
        </xs:complexType>
    </xs:element>


    <xs:simpleType name="distanciaPositiva">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0" />
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="distancia">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="distanciaPositiva">
                    <xs:attribute name="unidades" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="km" />
                                <xs:enumeration value="m" />
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>


    <xs:element name="fotografias">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="5" ref="fotografia" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="fotografia" type="xs:string" />


    <xs:element name="videos">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="3" ref="video" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="video" type="xs:string" />

    <xs:element name="planimetria" type="xs:string" />
    <xs:element name="altimetria" type="xs:string" />

</xs:schema>

=== Daniel-RodriguezFernandez/Avila-Desktop/xml/rutas.xml
<?xml version="1.0" encoding="UTF-8"?>
<rutas xmlns="http://www.uniovi.es"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.uniovi.es rutas.xsd">

    <ruta id="R01"
        nombre="AVILA CIUDAD"
        tipo="Arquitectura y Monumentos"
        medio="A pie"
        agencia="Sin agencia"
        recomendacion="7">

        <horario>
            <fecha_inicio>2026-05-14</fecha_inicio>
            <hora_inicio>17:30:00</hora_inicio>
            <duracion>PT2H50M</duracion>
        </horario>

        <descripcion>
            PASEO CIRCULAR POR LA CIUDAD DE AVILA ciudad tranquila que invita a disfrutar con calma del tiempo, el momento del atardecer desde el mirador de los Cuatro Postes. Está extramuros que al caer la noche, la vista de la muralla iluminada en la oscurida. 
        </descripcion>

        <personasAdecuadas>
            Se puede ir con niños
        </personasAdecuadas>

        <inicio>
            <lugar>Área de Autocaravanas de Ávila</lugar>
            <direccion>Calle Santa María de la Cabeza, 15, 05005, Ávila</direccion>
            <coordenadas>
                <longitud>-4.705003</longitud>
                <latitud>40.661846</latitud>
                <altitud>1070.271</altitud>
            </coordenadas>
        </inicio>

        <referencias>
            <referencia>https://es.wikiloc.com/rutas-a-pie/avila-ciudad-88004526#wp-88004534</referencia>
            <referencia>https://www.avilaturismo.com/en/home/</referencia>
            <referencia>https://www.komoot.com/es-es/guide/11731/rutas-de-senderismo-en-avila</referencia>
        </referencias>

        <hitos>
            <hito nombre="PASARELA">
                <descripcion>Arquitectura - Puentes</descripcion>
                <coordenadas>
                    <longitud>-4.707827</longitud>
                    <latitud>40.659532</latitud>
                    <altitud>1085</altitud>
                </coordenadas>
                <distancia unidades="km">0.4</distancia>
                <fotografias>
                    <fotografia>pasarela.jpg</fotografia>
                </fotografias>
            </hito>
            <hito nombre="">
                <descripcion></descripcion>
                <coordenadas>
                    <longitud>0</longitud>
                    <latitud>0</latitud>
                    <altitud>0</altitud>
                </coordenadas>
                <distancia unidades="km">0</distancia>
                <fotografias>
                    <fotografia></fotografia>
                </fotografias>
            </hito>
            <hito nombre="">
                <descripcion></descripcion>
                <coordenadas>
                    <longitud>0</longitud>
                    <latitud>0</latitud>
                    <altitud>0</altitud>
                </coordenadas>
                <distancia unidades="km">0</distancia>
                <fotografias>
                    <fotografia></fotografia>
                </fotografias>
            </hito>
            <hito nombre="">
                <descripcion></descripcion>
                <coordenadas>
                    <longitud>0</longitud>
                    <latitud>0</latitud>
                    <altitud>0</altitud>
                </coordenadas>
                <distancia unidades="km">0</distancia>
                <fotografias>
                    <fotografia></fotografia>
                </fotografias>
            </hito>
            <hito nombre="">
                <descripcion></descripcion>
                <coordenadas>
                    <longitud>0</longitud>
                    <latitud>0</latitud>
                    <altitud>0</altitud>
                </coordenadas>
                <distancia unidades="km">0</distancia>
                <fotografias>
                    <fotografia></fotografia>
                </fotografias>
            </hito>
        </hitos>

        <trazado>
            <coordenadas>
                <longitud>-4.705003</longitud>
                <latitud>40.661846</latitud>
                <altitud>1070.271</altitud>
            </coordenadas>
            <coordenadas>
                <longitud>-4.705006</longitud>
                <latitud>40.661842</latitud>
                <altitud>1070.341</altitud>
            </coordenadas>
            <coordenadas>
                <longitud>-4.705027</longitud>
                <latitud>40.661822</latitud>
                <altitud>1071.815</altitud>
            </coordenadas>
            <coordenadas>
                <longitud>-4.705098</longitud>
                <latitud>40.661723</latitud>
                <altitud>1071.808</altitud>
            </coordenadas>
            <coordenadas>
                <longitud>-4.705248</longitud>
                <latitud>40.66173</latitud>
                <altitud>1071.025</altitud>
            </coordenadas>
            <coordenadas>
                <longitud>-4.705318</longitud>
                <latitud>40.661752</latitud>
                <altitud>1071.055</altitud>
            </coordenadas>
            <coordenadas>
                <longitud>-4.705557</longitud>
                <latitud>40.661793</latitud>
                <altitud>1069.977</altitud>
            </coordenadas>
            <coordenadas>
                <longitud>-4.705573</longitud>
                <latitud>40.661796</latitud>
                <altitud>1069.977</altitud>
            </coordenadas>
            <coordenadas>
                <longitud>-4.705696</longitud>
                <latitud>40.661719</latitud>
                <altitud>1069.991</altitud>
            </coordenadas>
            <coordenadas>
                <longitud>-4.705768</longitud>
                <latitud>40.661583</latitud>
                <altitud>1069.982</altitud>
            </coordenadas>
            <coordenadas>
                <longitud>-4.705787</longitud>
                <latitud>40.661559</latitud>
                <altitud>1069.969</altitud>
            </coordenadas>
            <coordenadas>
                <longitud>-4.705846</longitud>
                <latitud>40.661421</latitud>
                <altitud>1071.163</altitud>
            </coordenadas>
            <coordenadas>
                <longitud>-4.705887</longitud>
                <latitud>40.661277</latitud>
                <altitud>1071.117</altitud>
            </coordenadas>
            <coordenadas>
                <longitud>-4.705909</longitud>
                <latitud>40.661245</latitud>
                <altitud>1071.187</altitud>
            </coordenadas>
            <coordenadas>
                <longitud>-4.7061</longitud>
                <latitud>40.661199</latitud>
                <altitud>1071.115</altitud>
            </coordenadas>
            <coordenadas>
                <longitud>-4.706146</longitud>
                <latitud>40.661185</latitud>
                <altitud>1071.108</altitud>
            </coordenadas>
            <coordenadas>
                <longitud>-4.706284</longitud>
                <latitud>40.661162</latitud>
                <altitud>1068.689</altitud>
            </coordenadas>
            <coordenadas>
                <longitud>-4.706574</longitud>
                <latitud>40.661084</latitud>
                <altitud>1065.639</altitud>
            </coordenadas>
            <coordenadas>
                <longitud>-4.706807</longitud>
                <latitud>40.66103</latitud>
                <altitud>1066.531</altitud>
            </coordenadas>
            <coordenadas>
                <longitud>-4.706912</longitud>
                <latitud>40.661003</latitud>
                <altitud>1062.861</altitud>
            </coordenadas>
            <coordenadas>
                <longitud>-4.706925</longitud>
                <latitud>40.660999</latitud>
                <altitud>1062.815</altitud>
            </coordenadas>
            <coordenadas>
                <longitud>-4.706975</longitud>
                <latitud>40.660983</latitud>
                <altitud>1065.756</altitud>
            </coordenadas>
            <coordenadas>
                <longitud>-4.707163</longitud>
                <latitud>40.660799</latitud>
                <altitud>1065.783</altitud>
            </coordenadas>
            <coordenadas>
                <longitud>-4.70718</longitud>
                <latitud>40.660751</latitud>
                <altitud>1063.427</altitud>
            </coordenadas>
            <coordenadas>
                <longitud>-4.707209</longitud>
                <latitud>40.660679</latitud>
                <altitud>1062.615</altitud>
            </coordenadas>
            <coordenadas>
                <longitud>-4.707498</longitud>
                <latitud>40.66062</latitud>
                <altitud>1058.865</altitud>
            </coordenadas>
            <coordenadas>
                <longitud>-4.707805</longitud>
                <latitud>40.660609</latitud>
                <altitud>1058.011</altitud>
            </coordenadas>
            <coordenadas>
                <longitud>-4.70786</longitud>
                <latitud>40.660586</latitud>
                <altitud>1058.008</altitud>
            </coordenadas>
            <coordenadas>
                <longitud>-4.707877</longitud>
                <latitud>40.660511</latitud>
                <altitud>1058.069</altitud>
            </coordenadas>
            <coordenadas>
                <longitud>-4.707837</longitud>
                <latitud>40.660275</latitud>
                <altitud>1058.079</altitud>
            </coordenadas>
            <coordenadas>
                <longitud>-4.707803</longitud>
                <latitud>40.660186</latitud>
                <altitud>1058.111</altitud>
            </coordenadas>
            <coordenadas>
                <longitud>-4.707804</longitud>
                <latitud>40.660129</latitud>
                <altitud>1058.111</altitud>
